############################################################
#
# Message
#
#  Author   : Koji HIJIKURO<koji.hijikuro@nms.necel.com>
#  Date     : 2009/07/27
#
############################################################
class Message
  def initialize(myname="Message")
    @name =myname
  end


  def print_base
    printf("%s ver:%s\n",$TOOL,$VERSION)
    printf("Copyright (c) 2009 NEC MicroSystem. All rights reserved.\n\n")
  end
  
  def print_usage
    printf("\n")
    printf("Usage : %s.rb [OPTION] <Conf file>/<-all>\n",$TOOL)
    printf(" OPTION:\n")
    printf("    -h/-help     : print help message\n")
    printf("    -v/-version  : print version\n")
    printf("    -verbose     : execute on verbose mode\n")
    printf("    -all         : execute all conf file\n")
    printf("    \n")
  end
  
  def print_file_header(f, str, tool = $TOOL, ver = $VERSION,c = "#")
    25.times{
      f.printf("%s",c)
    }
    f.printf("\n")
    f.printf("%s\n",c)
    f.printf("%s %s\n",c,str)
    f.printf("%s   Generated by %s ver:%s\n",c,tool, ver)
    f.printf("%s   Date: %s\n",c,Time.new)
    f.printf("%s\n",c)
    25.times{
      f.printf("%s",c)
    }
    f.printf("\n")
=begin
    f.printf("##################################################\n")
    f.printf("#\n")
    f.printf("# %s\n",str)
    f.printf("#   Generated by %s ver:%s\n",tool, ver)
    f.printf("#   Date: %s\n",Time.new)
    f.printf("#\n")
    f.printf("##################################################\n")
=end
  end

  def print_summary
    printf("\n")
    printf("Execution summary\n")
    printf("   Note     : %3d\n", $NOTE_CNT)
    printf("   Warning  : %3d\n", $WARNING_CNT)
    printf("   Error    : %3d\n", $ERROR_CNT)
    printf("\n")
    if $ERROR_CNT == 0
      printf("%s finished in successfully.\n",$TOOL)
    else
      printf("%s finished with Errors. please check error message.\n",$TOOL)
    end
  end

  def print_error
  end

  def print_warning
  end

end
