// Generated by XMLtoVerilog 1.2.6 at Undefined
/* [FromXML] xml version="1.0" encoding="UTF-8"*/
/* [FromXML] Generated by VerilogToXML 1.4.6 at 2013-02-01 13:13:39 */
/* [FromXML] included ".//home/m0001/rl0003/product/div-micom-ice/data/proj/RL78/Common/FICE/trunk/test/FMake/tp/1695.v" */
    
module TOP_EVA (OutSignal2, DOUT);
    wire FMakeWire_add_1695_DOUT4;
    wire [2:0] FMakeWire_sub001_sub002_sub003_KKK;
    wire [2:0] FMakeWire_out_mod_OutSignal;
    wire FMakeWire_sub001_sub002_sub003_sub004_out_mod2_DIN5;
    wire [2:0] FMakeWire_sub001_sub002_sub003_UUU;
    wire [2:0] FMakeWire_sub001_sub002_sub003_xxx;
    wire FMakeWire_sub001_sub002_sub003_sub004_c;
    output DOUT;
    wire DOUT;
    output OutSignal2;
    wire OutSignal2;
    wire a;
    Sub001 sub001 (.a(a), .OutSignal2(OutSignal2), .FMakeWire_sub002_sub003_sub004_c(FMakeWire_sub001_sub002_sub003_sub004_c), 
        .FMakeWire_sub002_sub003_xxx(FMakeWire_sub001_sub002_sub003_xxx[2:0]), .FMakeWire_sub002_sub003_UUU(FMakeWire_sub001_sub002_sub003_UUU[2:0]), 
        .FMakeWire_sub002_sub003_sub004_out_mod2_DIN5(FMakeWire_sub001_sub002_sub003_sub004_out_mod2_DIN5), 
        .FMakeWire_sub002_sub003_KKK(FMakeWire_sub001_sub002_sub003_KKK[2:0]), .FMakeWire_sub002_sub003_sub004_add_1695_DOUT4(FMakeWire_add_1695_DOUT4), 
        .FMakeWire_sub002_sub003_sub004_in_mod3_InSignal0(FMakeWire_add_1695_DOUT4));
    OutModule out_mod (.OutSignal0(), .OutSignal(FMakeWire_out_mod_OutSignal[2:0]));
    InModule in_mod0 (.InSignal(3'b0), .InSignal0(OutSignal2));
    InModule in_mod1 (.InSignal(3'b0), .InSignal0(1'b0));
    add_1695 add_1695 (.DOUT(DOUT), .DIN(FMakeWire_sub001_sub002_sub003_sub004_c), .DIN2(FMakeWire_sub001_sub002_sub003_xxx[2:0]), 
        .DIN3(FMakeWire_sub001_sub002_sub003_UUU[2:0]), .DIN5(FMakeWire_sub001_sub002_sub003_sub004_out_mod2_DIN5), 
        .DIN6(FMakeWire_out_mod_OutSignal[2:0]), .DIN4(FMakeWire_sub001_sub002_sub003_KKK[2:0]), .DOUT4(FMakeWire_add_1695_DOUT4));
endmodule 
    
module Sub001 (a, OutSignal2, FMakeWire_sub002_sub003_sub004_c, FMakeWire_sub002_sub003_xxx, FMakeWire_sub002_sub003_UUU, 
    FMakeWire_sub002_sub003_sub004_out_mod2_DIN5, FMakeWire_sub002_sub003_KKK, FMakeWire_sub002_sub003_sub004_add_1695_DOUT4, 
    FMakeWire_sub002_sub003_sub004_in_mod3_InSignal0);
    input FMakeWire_sub002_sub003_sub004_in_mod3_InSignal0;
    wire FMakeWire_sub002_sub003_sub004_in_mod3_InSignal0;
    input FMakeWire_sub002_sub003_sub004_add_1695_DOUT4;
    wire FMakeWire_sub002_sub003_sub004_add_1695_DOUT4;
    output [2:0] FMakeWire_sub002_sub003_KKK;
    wire [2:0] FMakeWire_sub002_sub003_KKK;
    output FMakeWire_sub002_sub003_sub004_out_mod2_DIN5;
    wire FMakeWire_sub002_sub003_sub004_out_mod2_DIN5;
    output [2:0] FMakeWire_sub002_sub003_UUU;
    wire [2:0] FMakeWire_sub002_sub003_UUU;
    output [2:0] FMakeWire_sub002_sub003_xxx;
    wire [2:0] FMakeWire_sub002_sub003_xxx;
    output FMakeWire_sub002_sub003_sub004_c;
    wire FMakeWire_sub002_sub003_sub004_c;
    output OutSignal2;
    wire OutSignal2;
    output a;
    wire a;
    wire c;
    OutModule2 out_mod (.OutSignal(), .OutSignal2(OutSignal2));
    Sub002 sub002 (.b(c), .FMakeWire_sub003_sub004_c(FMakeWire_sub002_sub003_sub004_c), .FMakeWire_sub003_xxx(FMakeWire_sub002_sub003_xxx[2:0]), 
        .FMakeWire_sub003_UUU(FMakeWire_sub002_sub003_UUU[2:0]), .FMakeWire_sub003_sub004_out_mod2_DIN5(FMakeWire_sub002_sub003_sub004_out_mod2_DIN5), 
        .FMakeWire_sub003_KKK(FMakeWire_sub002_sub003_KKK[2:0]), .FMakeWire_sub003_sub004_add_1695_DOUT4(FMakeWire_sub002_sub003_sub004_add_1695_DOUT4), 
        .FMakeWire_sub003_sub004_in_mod3_InSignal0(FMakeWire_sub002_sub003_sub004_in_mod3_InSignal0));
endmodule 
    
module Sub002 (b, FMakeWire_sub003_sub004_c, FMakeWire_sub003_xxx, FMakeWire_sub003_UUU, FMakeWire_sub003_sub004_out_mod2_DIN5, 
    FMakeWire_sub003_KKK, FMakeWire_sub003_sub004_add_1695_DOUT4, FMakeWire_sub003_sub004_in_mod3_InSignal0);
    input FMakeWire_sub003_sub004_in_mod3_InSignal0;
    wire FMakeWire_sub003_sub004_in_mod3_InSignal0;
    input FMakeWire_sub003_sub004_add_1695_DOUT4;
    wire FMakeWire_sub003_sub004_add_1695_DOUT4;
    output [2:0] FMakeWire_sub003_KKK;
    wire [2:0] FMakeWire_sub003_KKK;
    output FMakeWire_sub003_sub004_out_mod2_DIN5;
    wire FMakeWire_sub003_sub004_out_mod2_DIN5;
    output [2:0] FMakeWire_sub003_UUU;
    wire [2:0] FMakeWire_sub003_UUU;
    output [2:0] FMakeWire_sub003_xxx;
    wire [2:0] FMakeWire_sub003_xxx;
    output FMakeWire_sub003_sub004_c;
    wire FMakeWire_sub003_sub004_c;
    output b;
    wire e;
    Sub003 sub003 (.c(b), .d(e), .FMakeWire_sub004_c(FMakeWire_sub003_sub004_c), .xxx(FMakeWire_sub003_xxx[2:0]), 
        .UUU(FMakeWire_sub003_UUU[2:0]), .FMakeWire_sub004_out_mod2_DIN5(FMakeWire_sub003_sub004_out_mod2_DIN5), 
        .KKK(FMakeWire_sub003_KKK[2:0]), .FMakeWire_sub004_add_1695_DOUT4(FMakeWire_sub003_sub004_add_1695_DOUT4), 
        .FMakeWire_sub004_in_mod3_InSignal0(FMakeWire_sub003_sub004_in_mod3_InSignal0));
endmodule 
    
module Sub003 (c, d, FMakeWire_sub004_c, xxx, UUU, FMakeWire_sub004_out_mod2_DIN5, KKK, FMakeWire_sub004_add_1695_DOUT4, 
    FMakeWire_sub004_in_mod3_InSignal0);
    input FMakeWire_sub004_in_mod3_InSignal0;
    wire FMakeWire_sub004_in_mod3_InSignal0;
    input FMakeWire_sub004_add_1695_DOUT4;
    wire FMakeWire_sub004_add_1695_DOUT4;
    output [2:0] KKK;
    wire [2:0] KKK;
    output FMakeWire_sub004_out_mod2_DIN5;
    wire FMakeWire_sub004_out_mod2_DIN5;
    output [2:0] UUU;
    wire [2:0] UUU;
    output [2:0] xxx;
    output FMakeWire_sub004_c;
    wire FMakeWire_sub004_c;
    output c;
    output d;
    wire [2:0] xxx;
    Sub004 sub004 (.y(), .c(FMakeWire_sub004_c), .xxx(xxx), .UUU(UUU), .FMakeWire_out_mod2_DIN5(FMakeWire_sub004_out_mod2_DIN5), 
        .KKK(KKK), .FMakeWire_add_1695_DOUT4(FMakeWire_sub004_add_1695_DOUT4), .FMakeWire_in_mod3_InSignal0(FMakeWire_sub004_in_mod3_InSignal0));
endmodule 
    
module Sub004 (y, xxx, c, UUU, FMakeWire_out_mod2_DIN5, KKK, FMakeWire_add_1695_DOUT4, FMakeWire_in_mod3_InSignal0);
    input FMakeWire_in_mod3_InSignal0;
    wire FMakeWire_in_mod3_InSignal0;
    input FMakeWire_add_1695_DOUT4;
    wire FMakeWire_add_1695_DOUT4;
    output [2:0] KKK;
    output FMakeWire_out_mod2_DIN5;
    wire FMakeWire_out_mod2_DIN5;
    output [2:0] UUU;
    output c;
    output y;
    wire c;
    output [2:0] xxx;
    wire [2:0] xxx;
    wire [2:0] KKK;
    wire [2:0] addKKK;
    Sub005 sub005 (.f(xxx[2]), .d(c));
    Connect con (.DDD(c));
    wire [2:0] UUU;
    InModule in_mod (.InSignal(UUU), .InSignal0(1'b0));
    OutModule out_mod (.OutSignal(UUU), .OutSignal0());
    InModule in_mod2 (.InSignal(KKK), .InSignal0(FMakeWire_add_1695_DOUT4));
    OutModule out_mod2 (.OutSignal(KKK), .OutSignal0(FMakeWire_out_mod2_DIN5));
    InModule in_mod3 (.InSignal(KKK), .InSignal0(FMakeWire_in_mod3_InSignal0));
endmodule 
    
module Sub005 (d, f);
    output d;
    output f;
endmodule 
    
module Connect (DDD);
    input DDD;
endmodule 
    
module InModule (InSignal, InSignal0);
    input [2:0] InSignal;
    input InSignal0;
endmodule 
    
module OutModule (OutSignal, OutSignal0);
    output [2:0] OutSignal;
    output OutSignal0;
endmodule 
    
module OutModule2 (OutSignal, OutSignal2);
    output [2:0] OutSignal;
    output OutSignal2;
endmodule 
