define_attribute {p:RESETB}  xc_loc {U1};          # CN: 5, Pin:38 (O- 457)
define_attribute {p:clk}  xc_loc {AH22};           # CN: 1, Pin: 2 (O-   5)
define_attribute {p:rst}  xc_loc {AH23};           # CN: 1, Pin: 3 (O-   6)
define_attribute {p:D}  xc_loc {AH14};           # CN: 1, Pin: 4 (O-   7)
define_attribute {p:Q1}  xc_loc {AH13};           # CN: 1, Pin: 5 (O-   8)
define_attribute {p:Q2}  xc_loc {AH24};           # CN: 1, Pin: 6 (O-   9)
define_attribute {p:DOUT}  xc_loc {AJ24};           # CN: 1, Pin: 7 (O-  10)
define_attribute {p:Q3}  xc_loc {AJ14};           # CN: 1, Pin: 8 (O-  11)
define_attribute {p:cspf_Q3}  xc_loc {AH15};           # CN: 1, Pin: 9 (O-  12)
define_attribute {p:fpga_pio}  xc_loc {AJ22};         # CN: 1, Pin:10 (O-  13)
define_attribute {p:PTTL06}  xc_loc {AJ21};         # CN: 1, Pin:11 (O-  14)
define_attribute {p:PTTL07}  xc_loc {AJ11};         # CN: 1, Pin:12 (O-  15)
define_attribute {p:PTTL08}  xc_loc {AJ12};         # CN: 1, Pin:13 (O-  16)

