// Generated by XMLtoVerilog 1.2.6 at Undefined
/* [FromXML] xml version="1.0" encoding="UTF-8"*/
/* [FromXML] Generated by VerilogToXML 1.4.6 at 2013-02-01 13:14:09 */
/* [FromXML] included ".//home/m0001/rl0003/product/div-micom-ice/data/proj/RL78/Common/FICE/trunk/test/FMake/tp/BUS.v" */
    
module TOP_EVA ();
    PERICORE pericore (.p12_eni2());
endmodule 
    
module PERICORE (p12_eni2);
    output p12_eni2;
    P12 p12 (.eni({p12eni_2, p12eni_1, p12_eni0}));
    P12_IOBUF p12_iobuf (.eni({p12eni_2, p12eni_1, p12_eni0}));
endmodule 
    
module P12 (eni);
    output [2:0] eni;
endmodule 
    
module P12_IOBUF (eni);
    input [2:0] eni;
endmodule 
