// Generated by XMLtoVerilog 1.2.6 at Undefined
/* [FromXML] xml version="1.0" encoding="UTF-8"*/
/* [FromXML] Generated by VerilogToXML 1.4.6 at 2013-02-01 13:14:10 */
/* [FromXML] included ".//home/m0001/rl0003/product/div-micom-ice/data/proj/RL78/Common/FICE/trunk/test/FMake/tp/RESB.v" */
    
module TOP_EVA (ICE_RESB, RESB, STPST);
    wire FMakeWire_cspf_mp200_cpu_cpuwr;
    wire [2:0] FMakeWire_cspf_mp200_cpu_pb;
    wire [1:0] FMakeWire_cspf_mp200_pid;
    wire FMakeWire_cspf_mp200_ocd_SVSTOP;
    wire FMakeWire_svmodif2_SVSTOP;
    wire FMakeWire_ice_PID0;
    wire FMakeWire_ice_PID1;
    wire FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL0;
    wire FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL1;
    wire FMakeWire_pericore_dgen00;
    wire FMakeWire_pericore_dgen01;
    wire FMakeWire_pericore_dgen02;
    wire [2:0] cpu_pa;
    output STPST;
    wire STPST;
    output RESB;
    wire RESB;
    output ICE_RESB;
    wire ICE_RESB;
    wire rst_res_n2;
    wire SCAN_wire;
    CSPF cspf (.rst_res_n3(rst_res_n2), .rst(rst), .ICE_RESB(ICE_RESB), .cpu_pa(cpu_pa[2:0]), .FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1(FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL1), 
        .FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0(FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL0), .RESB(RESB), 
        .FMakeWire_mp200_csc_PID1(FMakeWire_ice_PID1), .FMakeWire_mp200_csc_PID0(FMakeWire_ice_PID0), 
        .FMakeWire_mp200_svmodif2_SVSTOP(FMakeWire_svmodif2_SVSTOP), .FMakeWire_mp200_ocd_SVSTOP(FMakeWire_cspf_mp200_ocd_SVSTOP), 
        .FMakeWire_mp200_pid(FMakeWire_cspf_mp200_pid[1:0]), .STPST(STPST), .FMakeWire_mp200_cpu_pb(FMakeWire_cspf_mp200_cpu_pb[2:0]), 
        .FMakeWire_mp200_cpu_cpuwr(FMakeWire_cspf_mp200_cpu_cpuwr));
    PERICORE pericore (.rst(ICE_RESB), .rst_res_n(RESB), .dgen02(FMakeWire_pericore_dgen02), .dgen01(FMakeWire_pericore_dgen01), 
        .dgen00(FMakeWire_pericore_dgen00));
    wwdt wwdt (.SCAN(SCAN_wire), .SCANCLK(1'b0));
    ICE ice (.PC1(1'b0), .ICE_RESB(ICE_RESB), .PA(cpu_pa[2:0]), .dgen02(FMakeWire_pericore_dgen02), .dgen01(FMakeWire_pericore_dgen01), 
        .dgen00(FMakeWire_pericore_dgen00), .RESB(RESB), .PID1(FMakeWire_ice_PID1), .PID0(FMakeWire_ice_PID0), 
        .CPUPID1(FMakeWire_cspf_mp200_pid[1]), .CPUPID0(FMakeWire_cspf_mp200_pid[0]), .STPST(STPST), 
        .PB2(FMakeWire_cspf_mp200_cpu_pb[2]), .PB1(FMakeWire_cspf_mp200_cpu_pb[1]), .PB0(FMakeWire_cspf_mp200_cpu_pb[0]), 
        .CPUWR(FMakeWire_cspf_mp200_cpu_cpuwr));
    svmodif2 svmodif2 (.ADCHSEL1(FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL1), .ADCHSEL0(FMakeWire_cspf_mp200_pgcsc_kerneltop_ADCHSEL0), 
        .SVSTOP(FMakeWire_svmodif2_SVSTOP), .SVSTOPICE(FMakeWire_cspf_mp200_ocd_SVSTOP), .CPUWR(FMakeWire_cspf_mp200_cpu_cpuwr));
endmodule 
    
module wwdt (SCAN, SCANCLK);
    input SCANCLK;
    output SCAN;
endmodule 
    
module CSPF (rst_res_n3, rst, ICE_RESB, RESB, STPST, cpu_pa, FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1, 
    FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0, FMakeWire_mp200_csc_PID1, FMakeWire_mp200_csc_PID0, FMakeWire_mp200_svmodif2_SVSTOP, 
    FMakeWire_mp200_ocd_SVSTOP, FMakeWire_mp200_pid, FMakeWire_mp200_cpu_pb, FMakeWire_mp200_cpu_cpuwr);
    output FMakeWire_mp200_cpu_cpuwr;
    wire FMakeWire_mp200_cpu_cpuwr;
    output [2:0] FMakeWire_mp200_cpu_pb;
    wire [2:0] FMakeWire_mp200_cpu_pb;
    output [1:0] FMakeWire_mp200_pid;
    wire [1:0] FMakeWire_mp200_pid;
    output FMakeWire_mp200_ocd_SVSTOP;
    wire FMakeWire_mp200_ocd_SVSTOP;
    input FMakeWire_mp200_svmodif2_SVSTOP;
    wire FMakeWire_mp200_svmodif2_SVSTOP;
    input FMakeWire_mp200_csc_PID0;
    wire FMakeWire_mp200_csc_PID0;
    input FMakeWire_mp200_csc_PID1;
    wire FMakeWire_mp200_csc_PID1;
    output FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0;
    wire FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0;
    output FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1;
    wire FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1;
    output [2:0] cpu_pa;
    wire [2:0] cpu_pa;
    output STPST;
    wire STPST;
    output RESB;
    wire RESB;
    output ICE_RESB;
    wire ICE_RESB;
    output rst_res_n3;
    output rst;
    wire rst_res_n;
    wire cpu_stpst;
    wire [1:0] adchsel;
    PGCSC2 pgcsc2 (.cpu_stpst(1'b0), .SVSTOP(1'b0), .dw(3'b0), .rst(ICE_RESB), .rst_res_n(RESB));
    MP200 mp200 (.rst_res_n(rst_res_n3), .rst(rst), .dummy_wire(dummy_wire), .adchsel(adchsel), .ICE_RESB(ICE_RESB), 
        .cpu_pa(cpu_pa), .FMakeWire_pgcsc_kerneltop_ADCHSEL1(FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1), 
        .FMakeWire_pgcsc_kerneltop_ADCHSEL0(FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0), .RESB(RESB), .FMakeWire_csc_PID1(FMakeWire_mp200_csc_PID1), 
        .FMakeWire_csc_PID0(FMakeWire_mp200_csc_PID0), .FMakeWire_svmodif2_SVSTOP(FMakeWire_mp200_svmodif2_SVSTOP), 
        .FMakeWire_ocd_SVSTOP(FMakeWire_mp200_ocd_SVSTOP), .pid(FMakeWire_mp200_pid[1:0]), .STPST(STPST), 
        .cpu_pb(FMakeWire_mp200_cpu_pb[2:0]), .cpu_cpuwr(FMakeWire_mp200_cpu_cpuwr));
    ModA mod_a (.A(rst_res_n), .cpu_stpst(cpu_stpst), .ADCHSEL1(FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL1), 
        .ADCHSEL0(FMakeWire_mp200_pgcsc_kerneltop_ADCHSEL0));
    ModB mod_b (.B(rst_res_n), .cpu_stpst(cpu_stpst));
endmodule 
    
module MP200 (rst_res_n, rst, dummy_wire, adchsel, ICE_RESB, RESB, STPST, cpu_pa, FMakeWire_pgcsc_kerneltop_ADCHSEL1, 
    FMakeWire_pgcsc_kerneltop_ADCHSEL0, FMakeWire_csc_PID1, FMakeWire_csc_PID0, FMakeWire_svmodif2_SVSTOP, 
    FMakeWire_ocd_SVSTOP, pid, cpu_pb, cpu_cpuwr);
    wire FMakeWire_cpu_CPU_OUT;
    output cpu_cpuwr;
    output [2:0] cpu_pb;
    output [1:0] pid;
    output FMakeWire_ocd_SVSTOP;
    wire FMakeWire_ocd_SVSTOP;
    input FMakeWire_svmodif2_SVSTOP;
    wire FMakeWire_svmodif2_SVSTOP;
    wire FCLK;
    input FMakeWire_csc_PID0;
    wire FMakeWire_csc_PID0;
    input FMakeWire_csc_PID1;
    wire FMakeWire_csc_PID1;
    output FMakeWire_pgcsc_kerneltop_ADCHSEL0;
    wire FMakeWire_pgcsc_kerneltop_ADCHSEL0;
    output FMakeWire_pgcsc_kerneltop_ADCHSEL1;
    wire FMakeWire_pgcsc_kerneltop_ADCHSEL1;
    output [2:0] cpu_pa;
    output STPST;
    wire STPST;
    output RESB;
    wire RESB;
    output ICE_RESB;
    wire ICE_RESB;
    output rst_res_n;
    output rst;
    wire rst_res_n;
    wire rst;
    wire [1:0] pid;
    wire [2:0] cpu_pa;
    wire [2:0] cpu_pb;
    wire [2:0] cpu_pc;
    output dummy_wire;
    wire [2:0] dw;
    wire cpu_cpuwr;
    output [1:0] adchsel;
    CSC csc (.PA2(cpu_pa[2]), .PA1(cpu_pa[1]), .PA0(cpu_pa[0]), .PB2(cpu_pb[2]), .PB1(cpu_pb[1]), .PB0(cpu_pb[0]), 
        .PC(cpu_pc), .CPUWR(cpu_cpuwr), .stpst(STPST), .ICE_RESB(ICE_RESB), .RESB(RESB), .PID1(FMakeWire_csc_PID1), 
        .PID0(FMakeWire_csc_PID0), .FCLK(FCLK), .SCANCLK(1'b0), .SVSTOP(FMakeWire_svmodif2_SVSTOP));
    CPU cpu (.PA2(cpu_pa[2]), .PA1(cpu_pa[1]), .PA0(cpu_pa[0]), .PC(cpu_pc), .dummy_wire(dummy_wire), 
        .dw2(dw[2]), .dw1(dw[1]), .dw0(dw[0]), .pd(pull_down001), .CPUBUS(), .rst(ICE_RESB), .rst_res_n(RESB), 
        .FCLK(FCLK), .EMEMRAMCLK(FCLK), .PID1(pid[1]), .PID0(pid[0]), .STPST(STPST), .PB2(cpu_pb[2]), 
        .PB1(cpu_pb[1]), .PB0(cpu_pb[0]), .CPUWR(cpu_cpuwr), .CPU_IN(FMakeWire_cpu_CPU_OUT), .CPU_OUT(FMakeWire_cpu_CPU_OUT));
    plldown_cell_pf pulldown_cell (.y(pull_down001));
    OCD ocd (.PB2(cpu_pb[2]), .PB1(cpu_pb[1]), .PB0(cpu_pb[0]), .SVSTOP(FMakeWire_ocd_SVSTOP));
    PGCSC pgcsc (.dw(dw[2:0]), .adchsel(adchsel), .rst(ICE_RESB), .rst_res_n(RESB), .cpu_stpst(STPST), 
        .FMakeWire_kerneltop_ADCHSEL1(FMakeWire_pgcsc_kerneltop_ADCHSEL1), .FMakeWire_kerneltop_ADCHSEL0(FMakeWire_pgcsc_kerneltop_ADCHSEL0), 
        .SVSTOP(FMakeWire_svmodif2_SVSTOP));
endmodule 
    
module plldown_cell_pf (y);
    output y;
    wire y = 1'b0;
endmodule 
    
module CSC (RESB, ICE_RESB, stpst, SVSTOP, PID1, PID0, PA2, PA1, PA0, PB2, PB1, PB0, PC, CPUWR, SCANCLK, 
    FCLK);
    output RESB;
    output ICE_RESB;
    input stpst;
    input SVSTOP;
    input PID1;
    input PID0;
    input PA2;
    input PA1;
    input PA0;
    input PB2;
    input PB1;
    input PB0;
    input [2:0] PC;
    input CPUWR;
    input SCANCLK;
    output FCLK;
endmodule 
    
module CPU (rst_res_n, rst, STPST, PID1, PID0, PA2, PA1, PA0, PB2, PB1, PB0, PC, dummy_wire, dw2, dw1, 
    dw0, pd, CPUWR, CPUBUS, CPU_OUT, CPU_IN, FCLK, EMEMRAMCLK);
    input rst_res_n;
    input rst;
    output PID1;
    output PID0;
    output STPST;
    output PA2;
    output PA1;
    output PA0;
    output PB2;
    output PB1;
    output PB0;
    output [2:0] PC;
    output dummy_wire;
    output dw2, dw1, dw0;
    input pd;
    output CPUWR;
    output [3:0] CPUBUS;
    output CPU_OUT;
    input CPU_IN;
    input FCLK;
    input EMEMRAMCLK;
endmodule 
    
module OCD (SVSTOP, PB2, PB1, PB0);
    output SVSTOP;
    input PB2;
    input PB1;
    input PB0;
endmodule 
    
module PGCSC (rst_res_n, rst, cpu_stpst, SVSTOP, dw, adchsel, FMakeWire_kerneltop_ADCHSEL1, FMakeWire_kerneltop_ADCHSEL0);
    output FMakeWire_kerneltop_ADCHSEL0;
    wire FMakeWire_kerneltop_ADCHSEL0;
    output FMakeWire_kerneltop_ADCHSEL1;
    wire FMakeWire_kerneltop_ADCHSEL1;
    input rst_res_n;
    input rst;
    input cpu_stpst;
    input SVSTOP;
    input [2:0] dw;
    output [1:0] adchsel;
    pgcsc_kerneltop kerneltop (.rst_res_n(rst_res_n), .rst(rst), .cpu_stpst(cpu_stpst), .ADCHSEL1(FMakeWire_kerneltop_ADCHSEL1), 
        .ADCHSEL0(FMakeWire_kerneltop_ADCHSEL0));
    pgcsc_kerneltop2 kerneltop2 (.rst_res_n(rst_res_n), .rst(rst), .cpu_stpst(cpu_stpst));
endmodule 
    
module pgcsc_kerneltop (rst_res_n, rst, cpu_stpst, ADCHSEL0, ADCHSEL1);
    input rst_res_n;
    input rst;
    input cpu_stpst;
    output ADCHSEL0;
    output ADCHSEL1;
endmodule 
    
module pgcsc_kerneltop2 (rst_res_n, rst, cpu_stpst);
    input rst_res_n;
    input rst;
    input cpu_stpst;
    mdiv mdiv01 (.rst_res_n(rst_res_n), .rst(rst), .cpu_stpst(cpu_stpst));
endmodule 
    
module pgcsc_kerneltop3 (rst_res_n, rst, cpu_stpst);
    input rst_res_n;
    input rst;
    input cpu_stpst;
endmodule 
    
module mdiv (rst_res_n, rst, cpu_stpst);
    input rst_res_n;
    input rst;
    input cpu_stpst;
endmodule 
    
module PERICORE (rst_res_n, rst, dgen02, dgen01, dgen00);
    output dgen00;
    output dgen01;
    output dgen02;
    input rst_res_n;
    input rst;
    wire dgen02, dgen01, dgen00;
    PORTIOTOP portiotop (.rst_res_n(rst_res_n), .rst(rst), .dgen({dgen02, dgen01, dgen00}));
    MC200 mc200 (.d2(dgen02), .d1(dgen01), .d0(dgen00));
endmodule 
    
module PORTIOTOP (rst_res_n, rst, dgen);
    input rst_res_n;
    input rst;
    output [2:0] dgen;
    wire [2:0] dgen;
    PORTTOP porttop (.rst_res_n(rst_res_n), .rst(rst), .dgen(dgen[2:0]));
endmodule 
    
module MC200 (d2, d1, d0);
    input d2, d1, d0;
endmodule 
    
module PORTTOP (rst_res_n, rst, dgen);
    input rst_res_n;
    input rst;
    output [2:0] dgen;
endmodule 
    
module ModA (A, cpu_stpst, ADCHSEL1, ADCHSEL0);
    input A;
    input cpu_stpst;
    input ADCHSEL1;
    input ADCHSEL0;
endmodule 
    
module ModB (B, cpu_stpst);
    output B;
    output cpu_stpst;
endmodule 
    
module PGCSC2 (rst_res_n, rst, cpu_stpst, SVSTOP, dw);
    input rst_res_n;
    input rst;
    input cpu_stpst;
    input SVSTOP;
    input [2:0] dw;
    pgcsc_kerneltop3 kerneltop3 (.rst_res_n(rst_res_n), .rst(rst), .cpu_stpst(cpu_stpst));
    pgcsc_kerneltop2 kerneltop2 (.rst_res_n(rst_res_n), .rst(rst), .cpu_stpst(cpu_stpst));
endmodule 
