#!/bin/sh

VerilogToXML ./hdl/FPGA_ICE_V5_Duty50_def.v
VerilogToXML ./hdl/DFlashEmu1.v
VerilogToXML ./hdl/MF3_Prim.v
VerilogToXML ./hdl/QAHIOS0BN32MV2_ICE.v
VerilogToXML ./hdl/QAHIOS1BN15KV1_ICE.v
VerilogToXML ./hdl/QAHMOS0HNV1_ICE.v
VerilogToXML ./hdl/QAHNFI4BN300NV1.v
VerilogToXML ./hdl/QAHREGOHNMAINV2_ICE.v
VerilogToXML ./hdl/QAHRES0CV1.v
VerilogToXML ./hdl/QAHSOS1HNV1_ICE.v
VerilogToXML ./hdl/QICAP015H5H.v
VerilogToXML ./hdl/QICAP025H5H.v
VerilogToXML ./hdl/QICAP035H5H.v
VerilogToXML ./hdl/QID04005_ICE.v
VerilogToXML ./hdl/QLK0RFCBM3SF1V1.v
VerilogToXML ./hdl/QLK0RIICAV2.v
VerilogToXML ./hdl/QLK0RMULDIV1V1_MUL_ICE_bb.v
VerilogToXML ./hdl/QLK0RRTC0V3.v
VerilogToXML ./hdl/QLK0RSAU02R2V1.v
VerilogToXML ./hdl/QLK0RSAU04R2V1.v
VerilogToXML ./hdl/QLK0RTAU08R2V1.v
VerilogToXML ./hdl/QLK0RWWDT1V2.v
VerilogToXML ./hdl/QNSC3NCP1V2.v
VerilogToXML ./hdl/QNSC3NCPDC0V1.v
VerilogToXML ./hdl/QNSC3NREG1V2.v
VerilogToXML ./hdl/TBFILTER1X2.v
VerilogToXML ./hdl/bforebreak.v
VerilogToXML ./hdl/break.v
VerilogToXML ./hdl/chiptop_058.v
VerilogToXML ./hdl/chiptop_other.v
VerilogToXML ./hdl/clockctl.v
VerilogToXML ./hdl/coverage.v
VerilogToXML ./hdl/d78f1070_v3.1_cf1.00_eva.hdl
VerilogToXML ./hdl/emem-SS3rd.v
VerilogToXML ./hdl/ememaltrom.v
VerilogToXML ./hdl/ememram-SS3rd.v
VerilogToXML ./hdl/ememrom-SS3rd.v
VerilogToXML ./hdl/eva_top_070.v
VerilogToXML ./hdl/evatop_other.v
VerilogToXML ./hdl/eventv1.v
VerilogToXML ./hdl/failsafev1.v
VerilogToXML ./hdl/g13_64_FixedPin_4.00.v
VerilogToXML ./hdl/host_interface.v
VerilogToXML ./hdl/iawif.v
VerilogToXML ./hdl/ice_other.v
VerilogToXML ./hdl/ice_top_SS3rd.v
VerilogToXML ./hdl/icescon_g13_64_dummy.v
VerilogToXML ./hdl/idversion.v
VerilogToXML ./hdl/ierl78clk240basev1.v
VerilogToXML ./hdl/ierl78orbusicedopv1.v
VerilogToXML ./hdl/ierl78prtyerrv1.v
VerilogToXML ./hdl/ierl78puctl7v1.v
VerilogToXML ./hdl/iirl78timerv1.v
VerilogToXML ./hdl/iirl78timetagv1.v
VerilogToXML ./hdl/kx4_busbridge.hdl
VerilogToXML ./hdl/kx4_capckgate.hdl
VerilogToXML ./hdl/kx4_caplio.v_RAMext
VerilogToXML ./hdl/kx4_capmux4.v
VerilogToXML ./hdl/kx4_caprio.v_noRAMext
VerilogToXML ./hdl/kx4_ckdist.hdl
VerilogToXML ./hdl/kx4_flashclk_dly.hdl
VerilogToXML ./hdl/kx4_iicascldly.hdl
VerilogToXML ./hdl/kx4_iicasdadly.hdl
VerilogToXML ./hdl/kx4_intor.hdl
VerilogToXML ./hdl/kx4_monsig.hdl
VerilogToXML ./hdl/kx4_piorv2.hdl
VerilogToXML ./hdl/kx4_porga.hdl
VerilogToXML ./hdl/kx4_port0v1.hdl
VerilogToXML ./hdl/kx4_port12v1.hdl
VerilogToXML ./hdl/kx4_port13v1.hdl
VerilogToXML ./hdl/kx4_port14v1.hdl
VerilogToXML ./hdl/kx4_port1v1_eva.hdl
VerilogToXML ./hdl/kx4_port2v1.hdl
VerilogToXML ./hdl/kx4_port3v1.hdl
VerilogToXML ./hdl/kx4_port4v1.hdl
VerilogToXML ./hdl/kx4_port5v1.hdl
VerilogToXML ./hdl/kx4_port6v1.hdl
VerilogToXML ./hdl/kx4_port7v1.hdl
VerilogToXML ./hdl/kx4_sdadly.hdl
VerilogToXML ./hdl/mask.v
VerilogToXML ./hdl/orbus-SS3rd.v
VerilogToXML ./hdl/port_iobuf.v
VerilogToXML ./hdl/pseudoemu.v
VerilogToXML ./hdl/qlk0radaa32v1_eva.v
VerilogToXML ./hdl/qlk0rcibcevam3sf1v1.hdl
VerilogToXML ./hdl/qlk0rcibcm3sf1v1_NVMCHK.hdl_100720
VerilogToXML ./hdl/qlk0rcibdm3sf1v1.hdl
VerilogToXML ./hdl/qlk0rcpueva0v3_101216.hdl
VerilogToXML ./hdl/qlk0rcrc0v1.hdl
VerilogToXML ./hdl/qlk0rcsc1v2_ICE.hdl
VerilogToXML ./hdl/qlk0rcsc1v2_eva.hdl
VerilogToXML ./hdl/qlk0rdmac0v1.hdl
VerilogToXML ./hdl/qlk0riaw0v1.hdl
VerilogToXML ./hdl/qlk0rint48v2.hdl
VerilogToXML ./hdl/qlk0rintm4v1.hdl_100206
VerilogToXML ./hdl/qlk0rintm8v1.hdl_100206
VerilogToXML ./hdl/qlk0rmaw0v1.hdl
VerilogToXML ./hdl/qlk0rmodectl2v1.hdl_nosec
VerilogToXML ./hdl/qlk0rmuldiv1v1.hdl
VerilogToXML ./hdl/qlk0rocd1v1.hdl
VerilogToXML ./hdl/qlk0rocd1v1_ICE.hdl
VerilogToXML ./hdl/qlk0rpclbuz1v1.hdl
VerilogToXML ./hdl/qlk0rpclbuz1v1_ICE.hdl
VerilogToXML ./hdl/qlk0rscon1v1.hdl
VerilogToXML ./hdl/qpk0rbbbb001v1.hdl
VerilogToXML ./hdl/qpk0rbbbb003v1.hdl
VerilogToXML ./hdl/qpk0rbbbb010v1.hdl
VerilogToXML ./hdl/qpk0rbbnn001v1.hdl
VerilogToXML ./hdl/qpk0rbbnn002v1.hdl
VerilogToXML ./hdl/qpk0rbcbb001v1.hdl
VerilogToXML ./hdl/qpk0rbcbb002v1.hdl
VerilogToXML ./hdl/qpk0rbcbb010v1.hdl
VerilogToXML ./hdl/qpk0rbcbb011v1.hdl
VerilogToXML ./hdl/qpk0rbcbb021v1.hdl
VerilogToXML ./hdl/qpk0rbcbb022v1.hdl
VerilogToXML ./hdl/qpk0rbcbb023v1.hdl
VerilogToXML ./hdl/qpk0rbcin001v1.hdl
VerilogToXML ./hdl/qpk0rbcin010v1.hdl
VerilogToXML ./hdl/qpk0rbcin011v1.hdl
VerilogToXML ./hdl/qpk0rbcon002v1.hdl
VerilogToXML ./hdl/qpk0rbdbb001v1.hdl
VerilogToXML ./hdl/qpk0rbdbb002v1.hdl
VerilogToXML ./hdl/qpk0rbdbb003v1.hdl
VerilogToXML ./hdl/qpk0rbdbb004v1.hdl
VerilogToXML ./hdl/qpk0rbdbb005v1.hdl
VerilogToXML ./hdl/qpk0rbdbb006v1.hdl
VerilogToXML ./hdl/qpk0rbdbb013v1.hdl
VerilogToXML ./hdl/qpk0rbdbb014v1.hdl
VerilogToXML ./hdl/qpk0rbdbb015v1.hdl
VerilogToXML ./hdl/qpk0rbdbb023v1.hdl
VerilogToXML ./hdl/qpk0rbdbb025v1.hdl
VerilogToXML ./hdl/qpk0rcbb02v1.hdl
VerilogToXML ./hdl/qpk0rcbb06v1.hdl
VerilogToXML ./hdl/qpk0rcbb13v1.hdl
VerilogToXML ./hdl/qpk0rccb03v1.hdl
VerilogToXML ./hdl/qpk0rccb04v1.hdl
VerilogToXML ./hdl/qpk0rcdb01v1.hdl
VerilogToXML ./hdl/qpk0rcdb05v1.hdl
VerilogToXML ./hdl/qpk0rceb00v1.hdl
VerilogToXML ./hdl/qpk0rcfb12v1.hdl
VerilogToXML ./hdl/qpk0rcfb14v1.hdl
VerilogToXML ./hdl/qpk0rcgb07v1.hdl
VerilogToXML ./hdl/qpk0rdb1v1.hdl
VerilogToXML ./hdl/qpk0rdc1v1.hdl
VerilogToXML ./hdl/qpk0rdd1v1.hdl
VerilogToXML ./hdl/qpk0rde1v1.hdl
VerilogToXML ./hdl/qpk0rdf1v1.hdl
VerilogToXML ./hdl/qpk0rdg1v1.hdl
VerilogToXML ./hdl/qpk0rkr08v1.hdl
VerilogToXML ./hdl/resetctl.v
VerilogToXML ./hdl/rl78g13adc10664cnt.hdl
VerilogToXML ./hdl/status.v
VerilogToXML ./hdl/svmodif.v
VerilogToXML ./hdl/test.v
VerilogToXML ./hdl/tracev1.v
